apiVersion: v1
kind: Pod
metadata:
  name: simple-wepapp-color
  labels:
    name: simple-wepapp-color
spec:
  containers:
  - name: simple-wepapp-color
    image: simple-wepapp-color
    ports:
      - containerPort: 8080
    resources:
      requests:
        memory: "1Gi"
        cpu: "1"
      limits:
        memory: "2Gi"
        cpu: "2"